# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"
ip_header = "CF-Connecting-IP"
address = "0.0.0.0"
port = 8080
workers = 1
keep_alive = 0
log_level = "normal"

[debug]
address = "0.0.0.0"
port = 8080
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log_level = "critical"
# NOTE: Don't (!) use this key! Generate your own and keep it private!
#       e.g. via `head -c64 /dev/urandom | base64`
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
key = "a release app-key"
extra = false